criteo/ios-publisher-sdk

.github/workflows/main.yml
Gemfile.lock

Adding a basic test workflow using https://github.com/maierj/fastlane-action

GitHub actions

---

.github/workflows/main.yml
README.md
fastlane/Fastfile

* Add badge: This was moslty to trigger actions workflow
* Fix trigger branches

[Actions] Fix & Improve workflow

---

.github/workflows/main.yml
CriteoPublisherSdk/CriteoPublisherSdk.xcodeproj/project.pbxproj
CriteoPublisherSdk/CriteoPublisherSdk.xcodeproj/xcshareddata/xcschemes/CriteoPublisherSdk.xcscheme
CriteoPublisherSdk/Tests/CriteoPublisherSdk.xctestplan
README.md
fastlane/Fastfile

Until fixed, these apparently require preprod access to work

Disable broken tests

---

CHANGELOG.md
CriteoPublisherSdk/Sources/Native/CRNativeAd+Internal.h
CriteoPublisherSdk/Sources/Native/CRNativeAd.h
CriteoPublisherSdk/Sources/Native/CRNativeAd.m
CriteoPublisherSdk/Tests/IntegrationTests/NativeAd/CR_NativeAdFunctionalTests.m
CriteoPublisherSdk/Tests/IntegrationTests/NativeAd/CR_NativeAdTableViewCell.h
CriteoPublisherSdk/Tests/IntegrationTests/NativeAd/CR_NativeAdTableViewCell.xib
CriteoPublisherSdk/Tests/IntegrationTests/NativeAd/CR_NativeAdTableViewController.m
CriteoPublisherSdk/Tests/IntegrationTests/NativeAd/SimpleViewController/CR_CustomNativeAdView.m
CriteoPublisherSdk/Tests/IntegrationTests/NativeAssetsFromCdb.json
CriteoPublisherSdk/Tests/UnitTests/Native/CRNativeAdTests.m
CriteoPublisherSdk/Tests/Utility/NetworkManager/CR_NetworkManagerSimulator.m

[Native] Add legal text

---

.github/workflows/main.yml

- We do not need fastlane action for now that does in fact bundle install
- Also add cache on bundle & cocoapods to improve job speed

[Actions] Switch from fastlane action to bundle

---

CriteoPublisherSdk/Sources/Configuration/CR_Config.h
CriteoPublisherSdk/Sources/Configuration/CR_Config.m
CriteoPublisherSdk/Tests/IntegrationTests/CR_WebApiIntegrationTests.m
CriteoPublisherSdk/Tests/Utility/Categories/CR_DependencyProvider+Testing.m

Remove that code from production logic to tests only
JIRA: EE-1001

[Config] Clean up preproduction testing code

---

CriteoPublisherSdk.xcworkspace/contents.xcworkspacedata
SupportFiles/SupportFiles.xcodeproj/project.pbxproj
fastlane/Fastfile

For easing working on Xcode & AppCode

[Xcode] Add project referencing support files

---

CHANGELOG.md
CriteoPublisherSdk/CriteoPublisherSdk.xcodeproj/project.pbxproj
CriteoPublisherSdk/CriteoPublisherSdk.xcodeproj/xcshareddata/xcschemes/CriteoPublisherSdk.xcscheme
CriteoPublisherSdk/Sources/CR_AdUnitHelper.m
CriteoPublisherSdk/Sources/CR_CacheManager.m
CriteoPublisherSdk/Sources/CR_CdbBid.h
CriteoPublisherSdk/Sources/CR_CdbBid.m
CriteoPublisherSdk/Sources/CR_DependencyProvider.h
CriteoPublisherSdk/Sources/CR_DependencyProvider.m
CriteoPublisherSdk/Sources/CR_HeaderBidding.h
CriteoPublisherSdk/Sources/CR_HeaderBidding.m
CriteoPublisherSdk/Sources/Configuration/CR_DeviceInfo.h
CriteoPublisherSdk/Sources/Configuration/CR_DeviceInfo.m
CriteoPublisherSdk/Sources/Display/CR_DisplaySizeInjector.h
CriteoPublisherSdk/Sources/Display/CR_DisplaySizeInjector.m
CriteoPublisherSdk/Sources/Standalone/CRInterstitial.m
CriteoPublisherSdk/Sources/Util/NSString+CriteoUrl.h
CriteoPublisherSdk/Sources/Util/NSString+CriteoUrl.m
CriteoPublisherSdk/Tests/IntegrationTests/CRInterstitialDelegateTests.m
CriteoPublisherSdk/Tests/IntegrationTests/CRInterstitialTests.m
CriteoPublisherSdk/Tests/IntegrationTests/CR_DfpInterstitialFunctionalTests.m
CriteoPublisherSdk/Tests/UnitTests/CR_AdUnitHelperTests.m
CriteoPublisherSdk/Tests/UnitTests/CR_BidManagerHelperTests.m
CriteoPublisherSdk/Tests/UnitTests/CR_CacheManagerTests.m
CriteoPublisherSdk/Tests/UnitTests/CR_CdbBidTests.m
CriteoPublisherSdk/Tests/UnitTests/CR_HeaderBiddingTests.m
CriteoPublisherSdk/Tests/UnitTests/Configuration/CR_DeviceInfoTests.m
CriteoPublisherSdk/Tests/UnitTests/Display/CR_DisplaySizeInjectorTests.m

Inject real size of interstitial at display time

---

CHANGELOG.md

Links have to be in a section to be properly set on GH releases

[changelog] Fix and improve

---

CriteoPublisherSdk/Tests/CriteoPublisherSdk.xctestplan
CriteoPublisherSdk/Tests/IntegrationTests/CRInterstitialTests.m

It was not just flaky but broken 🧐

[Tests] Fix and Re-enable Interstitial test

---

.github/workflows/main.yml

For manual triggering, for more details:
https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/

[github] Add workflow_dispatch

---

CriteoPublisherSdk/Tests/CriteoPublisherSdk.xctestplan

It was not just broken but also so much flaky 🧐

[Tests] Disable flaky CRInterstitialTests/testWithRendering

---

CriteoPublisherSdk/Sources/Feedback/CR_FeedbackController.m
CriteoPublisherSdk/Sources/Feedback/CR_FeedbackMessage.h
CriteoPublisherSdk/Sources/Feedback/CR_FeedbackMessage.m
CriteoPublisherSdk/Sources/Feedback/CR_FeedbackStorage+MessageUpdating.h
CriteoPublisherSdk/Sources/Feedback/CR_FeedbackStorage+MessageUpdating.m
CriteoPublisherSdk/Sources/Network/CR_ApiQueryKeys.h
CriteoPublisherSdk/Sources/Network/CR_ApiQueryKeys.m
CriteoPublisherSdk/Sources/Network/Serializers/CR_FeedbacksSerializer.m
CriteoPublisherSdk/Tests/IntegrationTests/CR_FeedbackMessageFunctionalTests.m
CriteoPublisherSdk/Tests/UnitTests/CR_BidManagerFeedbackTests.m
CriteoPublisherSdk/Tests/UnitTests/Feedback/CR_FeedbackControllerTests.m
CriteoPublisherSdk/Tests/UnitTests/Feedback/CR_FeedbackMessageTests.swift
CriteoPublisherSdk/Tests/UnitTests/Network/CR_FeedbackSerializerTests.swift
CriteoPublisherSdk/Tests/Utility/NetworkManager/CR_NetworkManagerSimulator.m

Inject zoneId coming from CDB in CSM

---

CHANGELOG.md
CriteoPublisherSdk/Sources/Standalone/CRBannerView.h
CriteoPublisherSdk/Sources/Standalone/CRBannerView.m
CriteoPublisherSdk/Sources/Standalone/CRInterstitial.h
CriteoPublisherSdk/Sources/Standalone/CRInterstitial.m
CriteoPublisherSdk/Tests/IntegrationTests/CRBannerViewDelegateTests.m
CriteoPublisherSdk/Tests/IntegrationTests/CRInterstitialTests.m
CriteoPublisherSdk/Tests/UnitTests/Standalone/CRBannerViewTests.m

`loadAdWithDisplayData` added to `CRBannerView` and `CRInterstitial`

Server side bidding

---

CriteoAdViewer/Sources/Info.plist
CriteoAdViewer/UITests/Info.plist
CriteoGoogleAdapter/Sources/CriteoGoogleAdapter/Info.plist
CriteoGoogleAdapter/Tests/CriteoGoogleAdapterTests/Info.plist
CriteoMoPubAdapter/Sources/CriteoMoPubAdapter/Info.plist
CriteoMoPubAdapter/Tests/CriteoMoPubAdapterTests/Info.plist
CriteoPublisherSdk.podspec
CriteoPublisherSdk/Sources/CRConstants.h
CriteoPublisherSdk/Sources/Info.plist
CriteoPublisherSdk/Tests/CriteoPublisherSdkTests-Info.plist
CriteoPublisherSdk/iTestHostApp/Info.plist

[Release] Bump to 3.10.0

---

tools/clang-format/clang-format-git-hook.sh

git add makes it unusable when committing partial files

[tools] Fix code format hook

---

CriteoPublisherSdk/Sources/CRConstants.h
CriteoPublisherSdk/Sources/CR_BidManager.m
CriteoPublisherSdk/Sources/CR_CdbBid.h
CriteoPublisherSdk/Sources/CR_CdbBid.m
CriteoPublisherSdk/Sources/Network/CR_ApiHandler.h
CriteoPublisherSdk/Sources/Network/CR_ApiHandler.m
CriteoPublisherSdk/Tests/IntegrationTests/CR_BidManagerIntegrationTests.m
CriteoPublisherSdk/Tests/UnitTests/CR_CdbBidTests.m

Also refactor the code a bit to improve code style and testability

Integration test: Bid Caching / "Immediate" bid (CPM > 0, TTL = 0) 

---

CriteoPublisherSdk/Tests/IntegrationTests/CR_BidManagerIntegrationTests.m

Integration test: Bid Caching / Expired bid

---

CriteoPublisherSdk/Tests/IntegrationTests/CR_BidManagerIntegrationTests.m
CriteoPublisherSdk/Tests/UnitTests/CR_BidManagerFeedbackTests.m
CriteoPublisherSdk/Tests/UnitTests/CR_BidManagerTests.m
CriteoPublisherSdk/Tests/UnitTests/CR_CdbBidTests.m
CriteoPublisherSdk/Tests/Utility/Builders/CR_CdbBidBuilder.h
CriteoPublisherSdk/Tests/Utility/Builders/CR_CdbBidBuilder.m
CriteoPublisherSdk/Tests/Utility/InHouseMediation/CR_TokenValue+Testing.m

Add noBid / silenced / immediate as they are commonly tested

[Tests] Improve bid builder and its usage

---

CHANGELOG.md
CriteoAdViewer/Sources/AdViewer/GoogleAdViewBuilder.swift
CriteoAdViewer/Sources/AdViewer/MopubAdViewBuilder.swift
CriteoAdViewer/Sources/GoogleDFP/GoogleDFPTableViewController.m
CriteoAdViewer/Sources/MopubHB/MopubTableViewController.m
CriteoPublisherSdk/Sources/CR_BidManager.h
CriteoPublisherSdk/Sources/CR_BidManager.m
CriteoPublisherSdk/Sources/Criteo.h
CriteoPublisherSdk/Sources/Criteo.m
CriteoPublisherSdk/Tests/IntegrationTests/CR_DfpBannerFunctionalTests.m
CriteoPublisherSdk/Tests/IntegrationTests/CR_DfpInterstitialFunctionalTests.m
CriteoPublisherSdk/Tests/IntegrationTests/CR_DfpNativeFunctionalTests.m
CriteoPublisherSdk/Tests/IntegrationTests/CR_HeaderBiddingDictionaryFunctionalTests.m
CriteoPublisherSdk/Tests/IntegrationTests/CR_IntegrationsTestBase.h
CriteoPublisherSdk/Tests/IntegrationTests/CR_IntegrationsTestBase.m
CriteoPublisherSdk/Tests/IntegrationTests/CR_MopubBannerFunctionalTests.m
CriteoPublisherSdk/Tests/IntegrationTests/CR_MopubInterstitialFunctionalTests.m
CriteoPublisherSdk/Tests/IntegrationTests/CR_ProfileIdFunctionalTests.m
CriteoPublisherSdk/Tests/UnitTests/CR_BidManagerTests.m

[Live Bidding] App Bidding integration

---

CHANGELOG.md
CriteoAdViewer/Sources/AdViewer/CriteoAdViewBuilder.swift
CriteoPublisherSdk/Sources/CR_BidManager.h
CriteoPublisherSdk/Sources/CR_BidManager.m
CriteoPublisherSdk/Sources/Criteo.h
CriteoPublisherSdk/Sources/Criteo.m
CriteoPublisherSdk/Sources/Native/CRNativeLoader+Internal.h
CriteoPublisherSdk/Sources/Native/CRNativeLoader.m
CriteoPublisherSdk/Sources/Standalone/CRBannerView.m
CriteoPublisherSdk/Sources/Standalone/CRInterstitial.m
CriteoPublisherSdk/Tests/IntegrationTests/CRInterstitialDelegateTests.m
CriteoPublisherSdk/Tests/IntegrationTests/CR_InHouseFunctionalTests.m
CriteoPublisherSdk/Tests/IntegrationTests/CR_ProfileIdFunctionalTests.m
CriteoPublisherSdk/Tests/PerformanceTests/CR_BidPerformanceTests.m
CriteoPublisherSdk/Tests/UnitTests/CR_BidManagerTests.m
CriteoPublisherSdk/Tests/UnitTests/CriteoTests.m

[Live Bidding] In-House integration

---

CriteoPublisherSdk/Sources/Configuration/CR_Config.h
CriteoPublisherSdk/Sources/Configuration/CR_Config.m
CriteoPublisherSdk/Sources/Configuration/CR_ConfigManager.m
CriteoPublisherSdk/Sources/Criteo.m
CriteoPublisherSdk/Sources/Util/NSUserDefaults+CR_Config.h
CriteoPublisherSdk/Sources/Util/NSUserDefaults+CR_Config.m
CriteoPublisherSdk/Tests/UnitTests/Configuration/CR_ConfigManagerTests.m
CriteoPublisherSdk/Tests/UnitTests/Configuration/CR_ConfigTests.m
CriteoPublisherSdk/Tests/UnitTests/CriteoTests.m
CriteoPublisherSdk/Tests/Utility/Categories/NSUserDefaults+Testing.h

Use CaC to enable/disable prefetch on init

---

CriteoPublisherSdk/Sources/Configuration/CR_Config.m
CriteoPublisherSdk/Sources/Util/NSUserDefaults+CR_Config.h
CriteoPublisherSdk/Sources/Util/NSUserDefaults+CR_Config.m
CriteoPublisherSdk/Tests/UnitTests/Configuration/CR_ConfigManagerTests.m
CriteoPublisherSdk/Tests/UnitTests/Configuration/CR_ConfigTests.m

So the name of the properties match the name of the CaC.

Rename *FeatureFlag by *Enabled

---

CriteoAdViewer/CriteoAdViewer.xcworkspace/contents.xcworkspacedata
CriteoAdViewer/CriteoAdViewer.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
CriteoAdViewer/Podfile
CriteoAdViewer/Podfile.lock
DEVELOPMENT.md

So we can test Sdk from CocoaPods instead of direct linking

[AdViewer][cocoapods] Test workspace and Podfile

---

CriteoAdViewer/Sources/AppDelegate.m

[SkAdNetwork] Call attribution method on startup

---

CriteoPublisherSdk/CriteoPublisherSdk.xcodeproj/project.pbxproj
CriteoPublisherSdk/Sources/CR_DependencyProvider.h
CriteoPublisherSdk/Sources/CR_DependencyProvider.m
CriteoPublisherSdk/Sources/Context/CRContextData+Internal.h
CriteoPublisherSdk/Sources/Context/CR_InternalContextProvider.h
CriteoPublisherSdk/Sources/Context/CR_InternalContextProvider.m
CriteoPublisherSdk/Sources/Network/CR_ApiHandler.h
CriteoPublisherSdk/Sources/Network/CR_ApiHandler.m
CriteoPublisherSdk/Sources/Network/CR_ApiQueryKeys.h
CriteoPublisherSdk/Sources/Network/CR_ApiQueryKeys.m
CriteoPublisherSdk/Sources/Network/Serializers/CR_BidRequestSerializer.h
CriteoPublisherSdk/Sources/Network/Serializers/CR_BidRequestSerializer.m
CriteoPublisherSdk/Sources/Standalone/CRBannerView+Internal.h
CriteoPublisherSdk/Tests/CriteoPublisherSdkTests-Bridging-Header.h
CriteoPublisherSdk/Tests/IntegrationTests/CR_ContextualFunctionalTests.m
CriteoPublisherSdk/Tests/UnitTests/Context/CR_InternalContextProviderTests.m
CriteoPublisherSdk/Tests/UnitTests/Network/CR_ApiHandlerTests.m
CriteoPublisherSdk/Tests/UnitTests/Network/CR_BidRequestSerializerSwiftTests.swift
CriteoPublisherSdk/Tests/UnitTests/Network/CR_BidRequestSerializerTests.m

Merge contexts and put them in CDB request

---

.github/workflows/release-cocoapods.yml
.github/workflows/release-github.yml
.github/workflows/test.yml
CriteoAdViewer/CriteoAdViewer.xcodeproj/xcshareddata/xcschemes/CriteoAdViewer.xcscheme
CriteoAdViewer/Sources/AdViewer/AdConfig.swift
CriteoAdViewer/Sources/AdViewer/AdvancedNativeView.swift
CriteoAdViewer/Sources/AdViewer/CriteoAdViewBuilder.swift
CriteoAdViewer/Sources/AdViewer/GoogleAdViewBuilder.swift
CriteoAdViewer/Sources/AdViewer/MopubAdViewBuilder.swift
CriteoAdViewer/Sources/NativeAd/CRVNativeAdView.h
CriteoGoogleAdapter/CriteoGoogleAdapter.xcodeproj/xcshareddata/xcschemes/CriteoGoogleAdapter.xcscheme
CriteoMoPubAdapter/CriteoMoPubAdapter.xcodeproj/xcshareddata/xcschemes/CriteoMoPubAdapter.xcscheme
CriteoMoPubAdapterTestApp/CriteoMoPubAdapterTestApp.xcodeproj/xcshareddata/xcschemes/CriteoMoPubAdapterTestApp.xcscheme
CriteoPublisherSdk/CriteoPublisherSdk.xcodeproj/xcshareddata/xcschemes/CriteoPublisherSdk.xcscheme
CriteoPublisherSdk/Sources/Native/CRNativeLoader.m
CriteoPublisherSdk/Sources/Public/CRNativeAd.h
CriteoPublisherSdk/Sources/Public/CRNativeAdView.h
CriteoPublisherSdk/Sources/Public/CRNativeLoader.h
CriteoPublisherSdk/Sources/Standalone/CRBannerView+Internal.h
CriteoPublisherSdk/Sources/Standalone/CRBannerView.m
CriteoPublisherSdk/Sources/Standalone/CRInterstitial+Internal.h
CriteoPublisherSdk/Sources/Standalone/CRInterstitial.m
CriteoPublisherSdk/Sources/Standalone/CR_InterstitialViewController.h
CriteoPublisherSdk/Tests/IntegrationTests/CR_DfpBannerFunctionalTests.m
CriteoPublisherSdk/Tests/UnitTests/Configuration/CR_DeviceInfoTests.m
CriteoPublisherSdk/Tests/UnitTests/Network/CR_BidRequestSerializerSwiftTests.swift
CriteoPublisherSdk/Tests/UnitTests/Standalone/CRBannerViewTests.m
CriteoPublisherSdk/Tests/Utility/Mocks/CRBannerViewDelegateMock.h
Gemfile.lock

- Upgrades Xcode to v12.2 as it is now the official version
- Update Gems
- Reformat some code
- Cleanup and uniformize imports

Updates & Cleanup

---

CriteoPublisherSdk/CriteoPublisherSdk.xcodeproj/project.pbxproj
CriteoPublisherSdk/Sources/CR_DependencyProvider.h
CriteoPublisherSdk/Sources/CR_DependencyProvider.m
CriteoPublisherSdk/Sources/Context/CR_InternalContextProvider.h
CriteoPublisherSdk/Sources/Context/CR_InternalContextProvider.m
CriteoPublisherSdk/Sources/Context/CR_Session.h
CriteoPublisherSdk/Sources/Context/CR_Session.m
CriteoPublisherSdk/Sources/Network/CR_Reachability.h
CriteoPublisherSdk/Sources/Network/CR_Reachability.m
CriteoPublisherSdk/Tests/CriteoPublisherSdk.xctestplan
CriteoPublisherSdk/Tests/CriteoPublisherSdkTests-Bridging-Header.h
CriteoPublisherSdk/Tests/UnitTests/Context/CR_InternalContextProviderTests.m
CriteoPublisherSdk/Tests/UnitTests/Network/CR_ApiHandlerTests.m
CriteoPublisherSdk/Tests/UnitTests/Network/CR_BidRequestSerializerSwiftTests.swift

[Contextual] Implement internal context provider

---

CHANGELOG.md
CriteoAdViewer/CriteoAdViewer.xcodeproj/xcshareddata/xcschemes/CriteoAdViewer.xcscheme
CriteoPublisherSdk/Sources/Criteo.m
CriteoPublisherSdk/Sources/Logging/CR_Logging.h
CriteoPublisherSdk/Sources/Logging/CR_Logging.m
CriteoPublisherSdk/Sources/Public/Criteo.h
CriteoPublisherSdk/Tests/CriteoPublisherSdk-Standalone.xctestplan
CriteoPublisherSdk/Tests/CriteoPublisherSdk.xctestplan
CriteoPublisherSdk/Tests/IntegrationTests/CR_LoggingFunctionalTests.m
CriteoPublisherSdk/Tests/UnitTests/Context/CR_InternalContextProviderTests.m

[Logging] Debug logs

---

CriteoPublisherSdk/Sources/Criteo.m
CriteoPublisherSdk/Tests/IntegrationTests/CR_LoggingFunctionalTests.m

Warning is troublesome with adapters that calls this at each call
JIRA: EE-1386

[Criteo][Logging] Log double register as info

---

CriteoPublisherSdk/Sources/DataConsent/CR_DataProtectionConsent.h
CriteoPublisherSdk/Sources/DataConsent/CR_DataProtectionConsent.m
CriteoPublisherSdk/Sources/Network/CR_ApiHandler.m
CriteoPublisherSdk/Sources/Network/CR_ApiQueryKeys.h
CriteoPublisherSdk/Sources/Network/CR_ApiQueryKeys.m
CriteoPublisherSdk/Sources/Network/Serializers/CR_BidRequestSerializer.m
CriteoPublisherSdk/Tests/UnitTests/Network/CR_ApiHandlerTests.m
CriteoPublisherSdk/Tests/Utility/Mocks/CR_DataProtectionConsentMock.h
CriteoPublisherSdk/Tests/Utility/Mocks/CR_DataProtectionConsentMock.m

Send the authorization status to GUM and CDB for iOS >= 14

---

CriteoPublisherSdk/Sources/CR_DependencyProvider.m
CriteoPublisherSdk/Sources/Logging/CR_RemoteLogHandler.h
CriteoPublisherSdk/Sources/Logging/CR_RemoteLogHandler.m
CriteoPublisherSdk/Tests/UnitTests/Logging/CR_RemoteLogHandlerTests.m

Disable RemoteLogs when consent is not given

---

CriteoPublisherSdk/Sources/DataConsent/CR_DataProtectionConsent.h
CriteoPublisherSdk/Sources/DataConsent/CR_DataProtectionConsent.m
CriteoPublisherSdk/Sources/Network/CR_ApiHandler.m
CriteoPublisherSdk/Sources/Network/CR_ApiQueryKeys.h
CriteoPublisherSdk/Sources/Network/CR_ApiQueryKeys.m
CriteoPublisherSdk/Tests/IntegrationTests/CR_HttpTests.m
CriteoPublisherSdk/Tests/UnitTests/Network/CR_ApiHandlerTests.m
CriteoPublisherSdk/Tests/Utility/Mocks/CR_DataProtectionConsentMock.h
CriteoPublisherSdk/Tests/Utility/Mocks/CR_DataProtectionConsentMock.m

[API] Remove deprecated limitedAdTracking

---

CriteoPublisherSdk/CriteoPublisherSdk.xcodeproj/project.pbxproj
CriteoPublisherSdk/Sources/Logging/CR_RemoteLogRecordSerializer.h
CriteoPublisherSdk/Sources/Logging/CR_RemoteLogRecordSerializer.m
CriteoPublisherSdk/Tests/UnitTests/Logging/CR_RemoteLogRecordSerializerTests.m

Add serializer for remote log records

---

CriteoPublisherSdk/Sources/CR_BidManager.h
CriteoPublisherSdk/Sources/CR_BidManager.m
CriteoPublisherSdk/Sources/CR_DependencyProvider.m
CriteoPublisherSdk/Sources/Logging/CR_RemoteLogHandler.h
CriteoPublisherSdk/Sources/Logging/CR_RemoteLogHandler.m
CriteoPublisherSdk/Tests/IntegrationTests/CR_LoggingFunctionalTests.m
CriteoPublisherSdk/Tests/UnitTests/Logging/CR_RemoteLogHandlerTests.m

Send remote logs at SDK init and after bid

---

CriteoAdViewer/Sources/AppDelegate.swift
CriteoAdViewer/Sources/Info.plist

[AdViewer] AppTrackingTransparency support

---

CriteoPublisherSdk/Sources/CR_HeaderBidding.m
CriteoPublisherSdk/Tests/UnitTests/CR_HeaderBiddingTests.m

[HeaderBidding] Fix enrich dictionary with interstitial

---

CriteoPublisherSdk/Sources/Native/CRMediaView.m

[Native] Set media view background transparent

---

CHANGELOG.md
CriteoPublisherSdk/Sources/Criteo+Internal.h
CriteoPublisherSdk/Sources/Criteo.m
CriteoPublisherSdk/Sources/DataConsent/CR_DataProtectionConsent.m
CriteoPublisherSdk/Tests/IntegrationTests/CR_LoggingFunctionalTests.m
CriteoPublisherSdk/Tests/UnitTests/Logging/CR_RemoteLogHandlerTests.m

[BugFix] Startup crash with TCF consent string

---

CriteoPublisherSdk/Sources/Logging/CR_Logging.m
CriteoPublisherSdk/Tests/UnitTests/Logging/CR_LoggingTests.m

Prevents infinite loops in case a log handler is emitting logs

[Logging] Recursive check

---

CHANGELOG.md
CriteoPublisherSdk/Sources/Configuration/CR_DeviceInfo.m

[DeviceInfo] Fix WebView dealloc on main thread

---

CriteoPublisherSdk/Sources/Configuration/CR_RemoteConfigRequest.m
CriteoPublisherSdk/Tests/UnitTests/Configuration/CR_RemoteConfigRequestTests.m
CriteoPublisherSdk/Tests/UnitTests/Network/CR_ApiHandlerTests.m

So we can configure per os
JIRA: DPP-3177

[Network][Config] Send device OS and Model

---

CriteoPublisherSdk/Sources/Criteo.m
CriteoPublisherSdk/Sources/Feedback/CR_FeedbackController.m
CriteoPublisherSdk/Sources/Network/CR_ApiHandler.m

- Log network errors as info (instead of warnings)
- Do not log localizedDescription
- Do not parse empty responses
JIRA: DPT-3233

[Logging] Improve logging

---

scripts/archive.sh
scripts/base.sh

Do not merge this, as cocoapods is temporarily disabled to test packaging from GitHub actions

📦️ Switch to xcframework format

---

CriteoPublisherSdk/CriteoPublisherSdk.xcodeproj/project.pbxproj

We were using absolute path instead of group relative one

🩹 Fix bad test plan path

---

CriteoAdViewer/Sources/AdViewer/MopubAdViewBuilder.swift

In test app, in order to properly load Mopub video units, we need to use a different AdUnit for Criteo bid request and Mopub request.
Passing AdConfig down the call chain to be able to change used CriteoAdUnitId for videos

fix(testAppMoPubVideo): Properly load videos for Mopub in testApp

---

CriteoAdViewer/Sources/AdViewer/AdConfig.swift
CriteoAdViewer/Sources/AdViewer/AdFormat.swift
CriteoAdViewer/Sources/AdViewer/AdNetwork.swift
CriteoAdViewer/Sources/AdViewer/AdViewerViewController.swift
CriteoAdViewer/Sources/AdViewer/GoogleAdViewBuilder.swift
CriteoPublisherSdk/Sources/CR_BidManager.m
CriteoPublisherSdk/Sources/CR_HeaderBidding.h
CriteoPublisherSdk/Sources/CR_HeaderBidding.m
CriteoPublisherSdk/Sources/Configuration/CR_Config.m
CriteoPublisherSdk/Sources/Criteo.m
CriteoPublisherSdk/Sources/Public/Criteo.h
CriteoPublisherSdk/Tests/IntegrationTests/CR_DfpRewardedFunctionalTests.m
CriteoPublisherSdk/Tests/UnitTests/CR_HeaderBiddingTests.m
wiremock/__files/vast.xml
wiremock/mappings/csm.json
wiremock/mappings/inapp-v2.json
wiremock/mappings/vast.json

Added rewarded ads in showcase app
Reworked the way integration are detected  when enriching requests. It no longer fails when the bid can not be retrieved properly.

Rewarded ad in showcase app

---

CHANGELOG.md

Updated changelog for 4.5.0 release

release(4.5.0): updated changelog for release

---

CriteoPublisherSdk/Sources/Network/CR_NetworkManager.m
CriteoPublisherSdk/Tests/UnitTests/Network/CR_NetworkManagerTests.m

handle exception on body serialization for POST request

DPP-4285: network manager - POST to URL body serialization crash fix

---

.github/workflows/release-cocoapods.yml
.github/workflows/release-github.yml

I have updated the Xcode version to 14.2 for CocoaPods release.

DPP-4249: updated xcode to 14 for cocoapods release

---

CriteoPublisherSdk/Sources/Configuration/CR_ConfigManager.m
CriteoPublisherSdk/Sources/Configuration/CR_RemoteConfigRequest.h
CriteoPublisherSdk/Sources/Configuration/CR_RemoteConfigRequest.m
CriteoPublisherSdk/Tests/UnitTests/Configuration/CR_RemoteConfigRequestTests.m
CriteoPublisherSdk/Tests/UnitTests/Network/CR_ApiHandlerTests.m
Podfile.lock

removed deviceId from get remote config request

remote config request update

---

CriteoPublisherSdk/Sources/MRAID/MRAIDFeature.swift

inline video feature now is set on bridge directly.

supports - removed inline video flag from data structure
